spring:
  task:
    scheduling:
      pool:
        size: 2
  jpa:
    properties:
      hibernate:
        format_sql: 'TRUE'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      max-lifetime: 840000
      idle-timeout: 300000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type.descriptor: WARN
      nodeValue: WARN
    root: INFO
    blog: WARN
    runtime: INFO
    instance class: INFO
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: ${JWT_EXPIRATION_TIME}
  jwtRefreshExpirationInMs: ${JWT_REFRESH_TIME}
  passwordResetExpirationInMs: ${PASSWORD_RESET_EXPIRATION}
  frontendUrl: ${FRONTEND_URL}
  ftpServer: ${FTP_SERVER}
  ftpPort: ${FTP_PORT}
  ftpUser: ${FTP_USER}
  ftpPassword: ${FTP_PASSWORD}

cloud:
  cloudName: ${CLOUD_NAME}
  apiKey: ${CLOUD_API_KEY}
  apiSecret: ${CLOUD_API_SECRET}
econt:
  api:
    urlCities: ${ECONT_API_GET_CITIES}
    urlOffices: ${ECONT_API_GET_OFFICES}
mailjet:
  api:
    key: ${MAILJET_API_KEY}
    secret: ${MAILJET_API_SECRET}
    sender: ${SENDER_EMAIL}
server:
  port: ${PORT:8080}